벡터와 행렬

파이썬에서는 차원에 상관없이 자료의 성질에 따라 리스트(list), 튜플(tuple), 딕셔너리(dictionary) 등으로 구분함

파이썬 기본 기능으로 행렬과 백터를 사용할 수 있지만 수치계산 등을 편하게 하기 위해서 numpy 패키지를 사용하여 백터와 행렬등의 배열을 사용하는 것이 더 편리함

In [1]:
import numpy as np

In [2]:
xv = np.array([1,2,3,4,5,6,7,8,9,10]);xv # 배열 : array 함수 사용

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
xv.__class__

numpy.ndarray

In [4]:
xv[3]=11;xv #xv 4번째 원소의 값을 바꿈

array([ 1,  2,  3, 11,  5,  6,  7,  8,  9, 10])

In [5]:
xv1 = np.arange(1,10);xv1 # 1 ~ 10-1까지 1씩 증가

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
xv2 = np.arange(1,10,2);xv2 # 1 ~ 10-1 까지 2씩 증가

array([1, 3, 5, 7, 9])

In [7]:
xv3 = np.arange(10);xv3 #0 ~ 10-1까지 1씩 증가

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
xv3[4]

4

In [9]:
xv[1:4] # 1~3 인덱스, 인덱스는 0부터 시작

array([ 2,  3, 11])

In [10]:
len(xv3) # 벡터의 길이 len 함수

10

In [11]:
xv3.size # 벡터의 길이, numpy 패키지의 size 메소드

10

In [12]:
np.array(range(1,10))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
a = range(1,10);a

range(1, 10)

In [14]:
np.array(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
xm = np.array([[1,2,3], [4,5,6], [7,8,9]]) # 행렬 생성, 한행 핸행 행렬 값을 설정

In [16]:
xm = np.arange(1,10) # 행렬 생성
xm = xm.reshape(3,3) # 행렬 생성
xm

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
xm = np.array(range(1,10)).reshape(3,3) # 행렬 생성
xm

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
xm.shape

(3, 3)

In [19]:
xm[1,2] # 2행 3열

6

In [20]:
xm[:, 0] # 모든행, 0열, xm[0:3, 0]

array([1, 4, 7])

In [21]:
xm[0:2, :] # 0~1행, 모든 열, xm[0:2, 0:3]

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
xm[0,2]=11

In [23]:
xm

array([[ 1,  2, 11],
       [ 4,  5,  6],
       [ 7,  8,  9]])

* 리스트 : 원소가 어떤 형태이든 상관없이 저장 가능, 행렬과 벡터라는 수학적 의미보다는 여러개를 하나의 이름으로 저장하기 위한 용도



In [24]:
a = [2, 3, 'c']
x = [1, 2, 'a', a]
print(x)

[1, 2, 'a', [2, 3, 'c']]


In [25]:
x[0] = 0; x[0] # array와 같은 방법으로 x[0] 값 위치 설정

0

In [26]:
x[3]

[2, 3, 'c']

In [27]:
x2 = [[1,2,3], [4,5,6], [7,8,9]] # 행렬 형태의 2차원 리스트
x2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [28]:
len(x2)

3

In [29]:
x2[0][2] # 0행 2열

3

In [30]:
x2[2] # 2차원 리스트의 경우 특정한 행 전체를 얻으려면 행번호만 []에 입력

[7, 8, 9]

In [31]:
[col[2] for col in x2] # 특정한 열을 얻기 위해 for문 사용

[3, 6, 9]

In [32]:
x2.reshape(3.3) # array가 아니라 리스트이으로 reshape를 사용할 수 없음

AttributeError: ignored

In [ ]:
x2.__class__

In [ ]:
type(x2)

* 튜플(tuple) : 리스트와 유사, 원소값 설정에 () 사용, 최초 설정된 이후 수정이 안됨

In [ ]:
tpl = (1,2,3)

In [ ]:
type(tpl)

In [ ]:
tpl[2]

In [ ]:
tpl[2] = 3

* 딕셔너리(Dictionary) : 인덱스가 0부터 시작하는 정수가 아니라, 사전처럼 특정한 이름을 갖도록 함

In [ ]:
country_code = {'korea':82, 'us':1, 'china':86}

In [ ]:
country_code

In [ ]:
print(country_code)

In [ ]:
print(len(country_code))

In [ ]:
print(country_code['korea'])

In [ ]:
print(country_code.keys()) # 키(Key)만 출력

In [ ]:
print(country_code.values()) # 해당 값만 출력

In [ ]:
print(country_code.items()) # 키와 값의 짝으로 출력

* 리스트와 배열 복사시 주의할 점

In [ ]:
xm = [[1,2,3], [4,5,6], [7,8,9]];xm

In [ ]:
xm2 = xm # xm 과 xm2는 같은 주소를 사용하여 저장됨. xm이나 xm2 중 하나만 값을 바꿔도 둘 다 바뀌게 됨

In [ ]:
xm2 = xm.copy()  # copy 사용하여 xm2를 만들어도 결과는 같음

In [ ]:
xm[0][0] = 10;xm2

In [ ]:
ym = [[1,2,3], [4,5,6], [7,8,9]]

In [ ]:
import copy as cp
ym2 = cp.deepcopy(ym)

In [ ]:
ym[0][0] = 10

In [ ]:
ym2[0][0] #ym[0][0] 의 값이 바뀔때 ym2[0][0]의 값은 바뀌지 않음