* 파이썬에서 벡터, 행렬 등 수학적인 연산은 아래 두가지 경우 차이가 있음
-  파이썬의 numpy 모듈의 ndarray 인 경우
-  기본 파이썬의 리스트, 튜플 인 경우

In [1]:
import numpy as np

In [2]:
x1 = [1,2,3,4]; x2 = [5,6,7,8]

In [3]:
y1 = np.array([1,2,3,4]); y2 = np.array([5,6,7,8])

In [4]:
print(x1+x2)

[1, 2, 3, 4, 5, 6, 7, 8]


In [5]:
print(x1+2) # 에러 발생, x1은 리스트, 2는 숫자라 연산이 안됨

TypeError: ignored

In [6]:
x1.__class__

list

In [7]:
type(x1)

list

In [8]:
print(x1+[2]) # x1뒤에 [2]를 추가(append)

[1, 2, 3, 4, 2]


In [9]:
print(y1+2) # numpy 모듈의 ndarray y1로 계산하면 연산이 됨

[3 4 5 6]


In [11]:
print(y1)

[1 2 3 4]


In [12]:
print(x1+x2) # 덧셈연산이 아닌 리스트의 연결 결과가 얻어짐

[1, 2, 3, 4, 5, 6, 7, 8]


In [15]:
print(y1+y2) # numpy 모듈의 ndarray 로 계산하면 덧셈 연산이 됨, 파이썬의 기본모듈보다 numpy 모듈을 사용하는 것이 유리함

[ 6  8 10 12]


* 파이썬의 벡터 연산(R과 유사한 형태)

In [17]:
xrow = np.array([1,2,3]); xrow # 행벡터

array([1, 2, 3])

In [21]:
xcol = np.array([[1],[2],[3]]); xcol # 열벡터

array([[1],
       [2],
       [3]])

In [25]:
print("dimensions: ", xrow.shape, xcol.shape) # xrow(행벡터) : 3개의 차원의 벡터, xcol(열벡터) : 3개의 행과 1개의 열을 가진 행렬

dimensions:  (3,) (3, 1)


In [26]:
print("xrow \n", xrow, "\n xcol: \n", xcol) # \n : 줄바꿈 특수문자

xrow 
 [1 2 3] 
 xcol: 
 [[1]
 [2]
 [3]]


In [28]:
aa = np.array(range(1,11))
bb = np.array(range(1,6))
cc = np.array([1,2,1,2,1])

In [34]:
aa

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
bb

array([1, 2, 3, 4, 5])

In [32]:
aa + bb # 길이가 같지 않아 에러 발생

ValueError: ignored

In [37]:
aa * 3 # aa 도든 원소 곱하기 3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [35]:
bb ** 2 # bb의 모든 원소 제곱, np.power(bb, 2) 와 같음

array([ 1,  4,  9, 16, 25])

* 행렬과 벡터의 항목 추가, 삭제 
* 파이썬의 첨자 연산 사용보다 numpy 패키지의 delete, append, insert 등의 함수를 사용하여 수행하는 것이 편리



In [39]:
import numpy as np
a = np.array(range(1,11,2))

In [48]:
a

array([1, 3, 5, 7, 9])

In [43]:
a1 = np.delete(a,2) # ndarray a에서 3번째 항목(인덱스 2) 삭제, 

In [42]:
a1

array([1, 3, 7, 9])

In [49]:
idx = [0,1,3] # 인덱스 0,1,3
a2 = np.delete(a, idx) # 한번에 여러게 삭제
a2

array([5, 9])

In [52]:
b1 = 11
a3 = np.append(a, b1) # ndarray a에 b1 추가

In [53]:
a3

array([ 1,  3,  5,  7,  9, 11])

In [55]:
b2 = 2
a4 = np.insert(a, 1, b2) # ndarray a 인덱스 2번째 위치에 b2를 삽입
a4

array([1, 2, 3, 5, 7, 9])

In [58]:
b3 = [1,2,3]
a5 = np.insert(a, 2, b3) # ndarray a 인덱스 3번째 위치에 b3를 삽입
a5

array([1, 3, 1, 2, 3, 5, 7, 9])

* 행렬에서의 추가, 삽입, 삭제

In [64]:
mx1 = np.array(range(1,10)).reshape(3,3)
mx1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
mx2 = np.append(mx1, np.array([10,20,30]).reshape(1,3), axis=0) # 행벡터 추가, axis=0 행
mx3 = np.append(mx1, np.array([10,20,30]).reshape(3,1), axis=1) # 열벡터 추가, axis=0 열

In [67]:
mx2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 20, 30]])

In [68]:
mx3

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20],
       [ 7,  8,  9, 30]])

* 행, 열 삭제

In [74]:
mx4 = np.delete(mx1, 0, axis=0) # mx1 행렬에서 첫째 행 삭제
mx5 = np.delete(mx1, [0,1], axis=1) # xm1 행렬에서 1,2 열 삭제

In [72]:
mx4

array([[4, 5, 6],
       [7, 8, 9]])

In [73]:
mx5

array([[3],
       [6],
       [9]])

* 행,열 삽입

In [77]:
mx6 = np.insert(mx1, 1, np.array([10,20,30]), axis=0) # mx1 행렬의 두번째 위치에 행으로 삽입
mx7 = np.insert(mx1, 1, np.array(range(10,100,10)).reshape(3,3), axis=1) # mx1 행렬의 두번째 위치에 열로 삽입

In [80]:
mx6

array([[ 1,  2,  3],
       [10, 20, 30],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [81]:
mx7

array([[ 1, 10, 40, 70,  2,  3],
       [ 4, 20, 50, 80,  5,  6],
       [ 7, 30, 60, 90,  8,  9]])

* 행렬의 곱

In [82]:
mtx = np.array([[1,2,3], [4,5,6]]) # numpy에서 ndarray 행렬 생성 <-- 리스트나 튜플 생성과 같이 각각의 행벡터를 입력

In [83]:
mtx

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
mtx = np.array([1,2,3,4,5,6]).reshape(2,3) # 벡터 값 입력 후 array 객체의 reshape 메소드를 사용하려 행, 열 수를 지정 할수도 있음

In [86]:
mtx

array([[1, 2, 3],
       [4, 5, 6]])

In [90]:
mx1 = np.array(range(1,7)).reshape(2,3)

In [91]:
mx2 = np.hstack((np.repeat(1,3).reshape(3,1),
                 np.repeat(2,3).reshape(3,1)))

In [105]:
mx2

array([[1, 2],
       [1, 2],
       [1, 2]])

In [99]:
np.repeat(1,3) # 1을 3번 반복

array([1, 1, 1])

In [100]:
np.repeat(1,3).reshape(3,1) # 3행 1열 행렬

array([[1],
       [1],
       [1]])

In [96]:
np.repeat(2,3) # 2를 3번 반복

array([2, 2, 2])

In [101]:
np.repeat(2,3).reshape(3,1) # 3행 1열 행렬

array([[2],
       [2],
       [2]])

In [106]:
np.hstack((np.repeat(1,3).reshape(3,1),
           np.repeat(2,3).reshape(3,1)))

array([[1, 2],
       [1, 2],
       [1, 2]])

In [92]:
mx5

array([[3],
       [6],
       [9]])

In [93]:
mx1

array([[1, 2, 3],
       [4, 5, 6]])

In [94]:
mx2

array([[1, 2],
       [1, 2],
       [1, 2]])

In [102]:
mx3 = np.matmul(mx1, mx2)

In [103]:
mx3

array([[ 6, 12],
       [15, 30]])

In [104]:
mx3.shape

(2, 2)