In [1]:
!pip install pandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

* Series : 각 원소가 이름을 갖는 1차원 혼합 자료형 배열
* DataFrame : 행이름과 열이름이 있는 크기 변경이 가능한 테이블 구조의 배열

In [3]:
s = Series([10, 20, 30], index=['a', 'b', 'c']); s

a    10
b    20
c    30
dtype: int64

In [5]:
df = DataFrame(s, columns=["A"]); df

A
a  10
b  20
c  30

In [6]:
s.__class__

pandas.core.series.Series

In [7]:
type(s)

pandas.core.series.Series

In [8]:
df.__class__

pandas.core.frame.DataFrame

In [9]:
type(df)

pandas.core.frame.DataFrame

* 리스트(list), 튜플(tuple) 자료형, numpy의 ndarray 클래스 객체들 
==> Series 나 DataFrame 으로 변환될 수 있음.

* Series에서 각 원소의 이름(label)은 index 인자를 이용하여 지정할 수 있음

* 인덱스에는 동일한 값이 반복되어 나타날 수 있음(중복허용).

* Series s는 넘파이의 3차원 벡터로 바뀌고 df는 넘파이의 3차원 열벡터로 바뀜

In [10]:
s.to_numpy()

array([10, 20, 30])

In [11]:
df.to_numpy()

array([[10],
       [20],
       [30]])

In [12]:
s.to_numpy().shape

(3,)

In [13]:
df.to_numpy().shape

(3, 1)

In [15]:
s.index

Index(['A'], dtype='object')

In [16]:
df.index

Index(['a', 'b', 'c'], dtype='object')

In [17]:
df.columns

Index(['A'], dtype='object')

In [22]:
d = {'one' : Series([1,2], index=['a', 'b']),
     'two' : Series([1,2,3], index=['a', 'b', 'c'])}

In [23]:
df = DataFrame(d); df

one  two
a  1.0    1
b  2.0    2
c  NaN    3

In [28]:
np.arange(4)

array([0, 1, 2, 3])

In [25]:
x = np.arange(4).reshape((2,2)); x

array([[0, 1],
       [2, 3]])

In [26]:
df = DataFrame(x); df

0  1
0  0  1
1  2  3

In [29]:
df.columns=["A", "B"]; df

A  B
0  0  1
1  2  3

In [30]:
df.index=[11,12]; df

A  B
11  0  1
12  2  3