In [ ]:
import statsmodels.api as sm # R 에 있는 data 를 불러와서 pandas, DataFrame으로 저장할 수 있음

In [ ]:
trees = sm.datasets.get_rdataset("trees")['data']; trees.head()

Girth  Height  Volume
0    8.3      70    10.3
1    8.6      65    10.3
2    8.8      63    10.2
3   10.5      72    16.4
4   10.7      81    18.8

In [ ]:
mtcars = sm.datasets.get_rdataset("mtcars")['data']; mtcars.head()

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
Mazda RX4          21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
Mazda RX4 Wag      21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
Datsun 710         22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
Hornet 4 Drive     21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

                   carb  
Mazda RX4             4  
Mazda RX4 Wag         4  
Datsun 710            1  
Hornet 4 Drive        1  
Hornet Sportabout     2

In [ ]:
iris = sm.datasets.get_rdataset("iris")["data"]; iris.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
trees.__class__

pandas.core.frame.DataFrame

In [ ]:
mtcars.__class__

pandas.core.frame.DataFrame

In [ ]:
iris.__class__

pandas.core.frame.DataFrame

In [ ]:
tree4 =  trees[0:4].copy(); tree4

Girth  Height  Volume
0    8.3      70    10.3
1    8.6      65    10.3
2    8.8      63    10.2
3   10.5      72    16.4

In [ ]:
tree4.index = ['B', 'E', 'C', 'A']; tree4

Girth  Height  Volume
B    8.3      70    10.3
E    8.6      65    10.3
C    8.8      63    10.2
A   10.5      72    16.4

In [ ]:
tree4[tree4>10] # Girth>10

Girth  Height  Volume
B    NaN      70    10.3
E    NaN      65    10.3
C    NaN      63    10.2
A   10.5      72    16.4

In [ ]:
tree4[tree4.Girth>10] # Girth>10

Girth  Height  Volume
A   10.5      72    16.4

In [ ]:
tree4["Girth"]>10 # Girth>10

B    False
E    False
C    False
A     True
Name: Girth, dtype: bool

In [ ]:
tree4[tree4.Height>65] # 열 Height>65

Girth  Height  Volume
B    8.3      70    10.3
A   10.5      72    16.4

In [ ]:
tree4['E':'C'] # 행이름 'E':'C'

Girth  Height  Volume
E    8.6      65    10.3
C    8.8      63    10.2

In [ ]:
tree4[['Girth','Height']] # 열이름 'Girth','Height'

Girth  Height
B    8.3      70
E    8.6      65
C    8.8      63
A   10.5      72

In [ ]:
tree4.iloc[[0,2],[0,1]] # 행인덱스 0,2, 열인덱스 0,1

Girth  Height
B    8.3      70
C    8.8      63

In [ ]:
tree4

Girth  Height  Volume
B    8.3      70    10.3
E    8.6      65    10.3
C    8.8      63    10.2
A   10.5      72    16.4

In [ ]:
tree4.iloc[:2,[0,1]] # 행인덱스 0,1, 열인덱스 0,1

Girth  Height
B    8.3      70
E    8.6      65

In [ ]:
tree4.iloc[:2,0:1] # 행인덱스 0,1, 열인덱스 0

Girth
B    8.3
E    8.6

In [ ]:
tree4.loc['E':'C']

Girth  Height  Volume
E    8.6      65    10.3
C    8.8      63    10.2

In [ ]:
tree4.loc[['E','C'],['Girth', 'Height']]

Girth  Height
E    8.6      65
C    8.8      63

In [ ]:
tree4.loc['E':'C', 'Girth':'Height']

Girth  Height
E    8.6      65
C    8.8      63

In [ ]:
tree4.T # 전치

B     E     C     A
Girth    8.3   8.6   8.8  10.5
Height  70.0  65.0  63.0  72.0
Volume  10.3  10.3  10.2  16.4

In [ ]:
tree4.sort_index()

Girth  Height  Volume
A   10.5      72    16.4
B    8.3      70    10.3
C    8.8      63    10.2
E    8.6      65    10.3

In [ ]:
tree4

Girth  Height  Volume
B    8.3      70    10.3
E    8.6      65    10.3
C    8.8      63    10.2
A   10.5      72    16.4

In [ ]:
tree4.sort_values('Height') # 'Height' 기준 오름순차 정렬

Girth  Height  Volume
C    8.8      63    10.2
E    8.6      65    10.3
B    8.3      70    10.3
A   10.5      72    16.4

In [ ]:
# import pandas as pd
# from pandas import DataFrame, Series
# pd.DataFrame(tree4).sort_values(0, ascending=False)

In [ ]:
tree4.mean()

Girth      9.05
Height    67.50
Volume    11.80
dtype: float64

In [ ]:
tree4.mean(1) # 0: 열 평균, 1: 행평균

B    29.533333
E    27.966667
C    27.333333
A    32.966667
dtype: float64

In [ ]:
tree4.cumsum() # 누적합계

Girth  Height  Volume
B    8.3      70    10.3
E   16.9     135    20.6
C   25.7     198    30.8
A   36.2     270    47.2

In [ ]:
import numpy as np
tree4.apply(np.cumsum)

Girth  Height  Volume
B    8.3      70    10.3
E   16.9     135    20.6
C   25.7     198    30.8
A   36.2     270    47.2

In [ ]:
a = tree4.apply(np.cumsum) # apply 데이터프레임의 지정된 축 방향으로 함수 적용

In [ ]:
a.__class__

pandas.core.frame.DataFrame

In [ ]:
tree4.apply(lambda x: x.max()) # lambda 함수를 안만들고 최대값 리턴 함수를 수행

Girth     10.5
Height    72.0
Volume    16.4
dtype: float64

In [ ]:
mtx = mtcars[['mpg', 'cyl', 'hp', 'gear']].copy(); mtx.head()

mpg  cyl   hp  gear
Mazda RX4          21.0    6  110     4
Mazda RX4 Wag      21.0    6  110     4
Datsun 710         22.8    4   93     4
Hornet 4 Drive     21.4    6  110     3
Hornet Sportabout  18.7    8  175     3

In [ ]:
pd.crosstab(mtx.cyl, mtx.gear) # crosstab : 데이터프레임에서 2개 이상의 명목변수에 대한 도수 계산

gear   3  4  5
cyl           
4      1  8  2
6      2  4  1
8     12  0  2

In [ ]:
mtn = mtx.groupby(by=['cyl', 'gear']).mean(); mtn # 데이터베이스 group by 기능

mpg          hp
cyl gear                    
4   3     21.500   97.000000
    4     26.925   76.000000
    5     28.200  102.000000
6   3     19.750  107.500000
    4     19.750  116.500000
    5     19.700  175.000000
8   3     15.050  194.166667
    5     15.400  299.500000

In [ ]:
print(mtn['mpg'])

cyl  gear
4    3       21.500
     4       26.925
     5       28.200
6    3       19.750
     4       19.750
     5       19.700
8    3       15.050
     5       15.400
Name: mpg, dtype: float64


In [ ]:
mtn['mpg'].unstack(0) # unstack(0) : munti index(4,6,8)를 열방향 우선으로

cyl        4      6      8
gear                      
3     21.500  19.75  15.05
4     26.925  19.75    NaN
5     28.200  19.70  15.40

In [ ]:
mtn['mpg'].unstack(1) # unstack(1) :  munti index(4,6,8)를 행방향 우선으로

gear      3       4     5
cyl                      
4     21.50  26.925  28.2
6     19.75  19.750  19.7
8     15.05     NaN  15.4

In [ ]:
mtn.index

MultiIndex([(4, 3),
            (4, 4),
            (4, 5),
            (6, 3),
            (6, 4),
            (6, 5),
            (8, 3),
            (8, 5)],
           names=['cyl', 'gear'])

In [ ]:
mi = mtn.index

In [ ]:
lvs0 = mi.levels[0]; cds0 = mi.codes[0]

In [ ]:
lvs0

Int64Index([4, 6, 8], dtype='int64', name='cyl')

In [ ]:
cds0

array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int8)

In [ ]:
lvx0 = lvs0[cds0].values; lvx0

array([4, 4, 4, 6, 6, 6, 8, 8])

In [ ]:
lvs1 = mi.levels[1]; cds1 = mi.codes[1]

In [ ]:
lvs1

Int64Index([3, 4, 5], dtype='int64', name='gear')

In [ ]:
cds1

array([0, 1, 2, 0, 1, 2, 0, 2], dtype=int8)

In [ ]:
lvx1 = lvs1[cds1].values; lvx1

array([3, 4, 5, 3, 4, 5, 3, 5])

In [ ]:
mpgx = mtn['mpg'].to_numpy(); mpgx

array([21.5  , 26.925, 28.2  , 19.75 , 19.75 , 19.7  , 15.05 , 15.4  ])

In [ ]:
d = {mi.names[0]: lvx0, mi.names[1]: lvx1, 'mpg':mpgx}; d

{'cyl': array([4, 4, 4, 6, 6, 6, 8, 8]),
 'gear': array([3, 4, 5, 3, 4, 5, 3, 5]),
 'mpg': array([21.5  , 26.925, 28.2  , 19.75 , 19.75 , 19.7  , 15.05 , 15.4  ])}

In [ ]:
from pandas import DataFrame, Series
mpga = DataFrame(d); mpga

cyl  gear     mpg
0    4     3  21.500
1    4     4  26.925
2    4     5  28.200
3    6     3  19.750
4    6     4  19.750
5    6     5  19.700
6    8     3  15.050
7    8     5  15.400

In [ ]:
mpga.pivot(index = 'gear', columns = 'cyl', values = 'mpg') # mtn['mpg'].unstack(0) 메소드 적용 결과와 동일

cyl        4      6      8
gear                      
3     21.500  19.75  15.05
4     26.925  19.75    NaN
5     28.200  19.70  15.40

In [ ]:
# join 함수와 merge 함수 (예제 추가예정)

In [20]:
dataL = [['n0', 'a0', 'b0', 'c0'], ['n0', 'a1', 'b1', 'c1'], ['n0', 'a2', 'b2', 'c2'], ['n1', 'a3', 'b3', 'c3']] 

In [21]:
dataL

[['n0', 'a0', 'b0', 'c0'],
 ['n0', 'a1', 'b1', 'c1'],
 ['n0', 'a2', 'b2', 'c2'],
 ['n1', 'a3', 'b3', 'c3']]

In [22]:
import pandas as pd
dfL = pd.DataFrame(dataL)
dfL

0   1   2   3
0  n0  a0  b0  c0
1  n0  a1  b1  c1
2  n0  a2  b2  c2
3  n1  a3  b3  c3

In [28]:
dfL.columns = ["N", "A", "B", "C"]; dfL

N   A   B   C
0  n0  a0  b0  c0
1  n0  a1  b1  c1
2  n0  a2  b2  c2
3  n1  a3  b3  c3

In [23]:
dataR = [['n0', 'a0', 'b0', 'd0'], ['n0', 'a1', 'b1', 'd1'], ['n1', 'a2', 'b2', 'd2'], ['n1', 'a3', 'b3', 'd3']] 

In [24]:
dataR

[['n0', 'a0', 'b0', 'd0'],
 ['n0', 'a1', 'b1', 'd1'],
 ['n1', 'a2', 'b2', 'd2'],
 ['n1', 'a3', 'b3', 'd3']]

In [25]:
import pandas as pd
dfR = pd.DataFrame(dataR)
dfR

0   1   2   3
0  n0  a0  b0  d0
1  n0  a1  b1  d1
2  n1  a2  b2  d2
3  n1  a3  b3  d3

In [30]:
dfR.columns = ["N", "A", "B", "D"]; dfR

N   A   B   D
0  n0  a0  b0  d0
1  n0  a1  b1  d1
2  n1  a2  b2  d2
3  n1  a3  b3  d3

In [31]:
pd.merge(dfL, dfR, on='N')

N A_x B_x   C A_y B_y   D
0  n0  a0  b0  c0  a0  b0  d0
1  n0  a0  b0  c0  a1  b1  d1
2  n0  a1  b1  c1  a0  b0  d0
3  n0  a1  b1  c1  a1  b1  d1
4  n0  a2  b2  c2  a0  b0  d0
5  n0  a2  b2  c2  a1  b1  d1
6  n1  a3  b3  c3  a2  b2  d2
7  n1  a3  b3  c3  a3  b3  d3

In [37]:
df = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3', 'K4', 'K5'],
                   'A': ['A0', 'A1', 'A2', 'A3', 'A4', 'A5']});df

key   A
0  K0  A0
1  K1  A1
2  K2  A2
3  K3  A3
4  K4  A4
5  K5  A5

In [39]:
other = pd.DataFrame({'key': ['K0', 'K1', 'K2'],
                      'B': ['B0', 'B1', 'B2']}); other

key   B
0  K0  B0
1  K1  B1
2  K2  B2

In [44]:
df.join(other, how='inner', lsuffix='_caller', rsuffix='_other') # how : left(기본값), right, inner lsuffix 왼쪽 접두어, rsuffix 오른쪽 접미어

key_caller   A key_other   B
0         K0  A0        K0  B0
1         K1  A1        K1  B1
2         K2  A2        K2  B2

In [57]:
dfL.join(dfR, on='N')

ValueError: ignored

In [47]:
df.set_index('key').join(other.set_index('key'), how='inner')

A   B
key        
K0   A0  B0
K1   A1  B1
K2   A2  B2

In [46]:
df.join(other.set_index('key'), how='inner', on='key')

key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2

In [ ]:
# concat 함수 (예제 추가예정)